### ISSUE TITLE
Update to Zabbix 6.4

### ISSUE THREAD

**Issue by bforpc** [bartmichu/zfs-zabbix-userparams#1]
Is there an update available to zabbix 6.4?
I have installed it liek described, but in zabbix Server nothing happen - no data from Client, no errors.
The zfs.userparams.conf are available, the commands inside are executable as zabbix user.
What can be wrong?

bfo

**Comment by bartmichu** [comment]
Hi @bforpc. I always try to update to the latest LTS version. Version 6.4 is not such a version, and it has too short of a support period for me.

But to be honest, I'm not sure whether your issue stems from the version you're using. There are a few things that need to be checked.

First of all, let's double-check each and every step from the 'usage' section.

Next, check if the location where you placed the `zfs-userparams.conf` file is included in the client's `Include` configuration option. For example, if you placed it under `/etc/zabbix/zabbix_agent2.d` then you would need something like `Include=/etc/zabbix/zabbix_agent2.d/*.conf` in your config.

Also, try to increase the `Timeout` value to `30`.

**Comment by zhuccc** [comment]
I'm put zfs-userparams.conf to /etc/zabbix/zabbix_agent2.d/ .
And restart agent.
But agent is not work.

/var/log/zabbix/zabbix_agent2.log is show Zabbix Agent 2 stopped. (6.4.9)
And I rename zfs-userparams.conf to zfs-userparams.con
The agent is work

**Comment by zhuccc** [comment]
However, I manually copied the contents of zfs-userparams.conf to zabbix-agnet2.conf
And it work！

**Comment by bartmichu** [comment]
@zhuccc I'm glad it works for you, thanks for sharing your solution

**Comment by bartmichu** [comment]
I'm closing it as it seems to be resolved.

**Comment by tukanos** [comment]
I have Zabbix server 6.4 and zabbix client 6.0.14.

I have manged to get it working with the `zfs-userparams.conf`.  The main issue was that the `Hostname` in the `zabbix_agetn2.conf` must match the name in the Zabbix server 6.4 configuration.
